# Generated by Django 4.2.4 on 2023-09-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor_first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('doctor_last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('doctor_email_address', models.EmailField(max_length=100, verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Specialism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialism_name', models.CharField(max_length=250, verbose_name='Specialism Name')),
                ('specialism_description', models.CharField(max_length=1000, verbose_name='Specialism Description')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital_name', models.CharField(max_length=250, verbose_name='Name')),
                ('hospital_address', models.CharField(max_length=250, verbose_name='Address')),
                ('hospital_postcode', models.CharField(max_length=250, verbose_name='Postcode')),
                ('hospital_email_address', models.EmailField(max_length=250, verbose_name='Email Address')),
                ('hospital_phone_number', models.CharField(max_length=250, verbose_name='Phone Number')),
                ('hospital_doctors', models.ManyToManyField(blank=True, to='website.doctor_record')),
            ],
        ),
        migrations.AddField(
            model_name='doctor_record',
            name='doctor_specialism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.doctor_specialism'),
        ),
    ]
